contexts:
  default:
    defaultProvider: docker
    options:
      DOTFILES_URL:
        userProvided: true
        value: https://github.com/nfrith/dotfiles
    providers:
      docker:
        creationTimestamp: "2025-01-01T00:00:00Z"
        initialized: true
        options:
          DOCKER_BUILDER: {}
          DOCKER_HOST: {}
          DOCKER_PATH:
            value: docker
          INACTIVITY_TIMEOUT: {}
defaultContext: default